language: ruby
#cache: bundler
rvm:
  - 2.4.0
  - 2.5.5
  - 2.6.3

before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle install
  - bundle exec jekyll build
notifications:
  email: false
  
branches:
  only:
    - release

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false

deploy:
  provider: pages
  local-dir: ./_site
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: release
